version: "3.8"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`status.oltinchain.com`)"
      - "traefik.http.routers.uptime.tls.certresolver=le"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"

volumes:
  uptime-kuma-data:

networks:
  web:
    external: true
