# mypy: ignore-errors
"""PR-2 bank connector, withdrawals and chain indexer tables.

Revision ID: 004
Revises: 003
Create Date: 2026-07-18

Hand-written (NOT autogenerated): env.py deliberately omits the orphan
exchange/staking model modules, so autogenerate would propose dropping the
exchange/staking tables created in 001. One migration for all four PR-2 tables,
consistent with 001.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "004"
down_revision: str | None = "003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # reserve_attestations — UNIQUE(audit_ref) for A2 idempotency.
    op.create_table(
        "reserve_attestations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column("grams", sa.BigInteger(), nullable=False),
        sa.Column("audit_ref", sa.String(128), nullable=False),
        sa.Column("tx_hash", sa.String(66), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.UniqueConstraint("audit_ref", name="uq_reserve_attestation_audit_ref"),
    )

    # bank_deposits — UNIQUE(bank_tx_id) for A2 idempotency.
    op.create_table(
        "bank_deposits",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("bank_tx_id", sa.String(128), nullable=False),
        sa.Column("amount_uzs", sa.BigInteger(), nullable=False),
        sa.Column("amount_wei", sa.String(80), nullable=False),
        sa.Column("tx_hash", sa.String(66), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.UniqueConstraint("bank_tx_id", name="uq_bank_deposit_bank_tx_id"),
    )
    op.create_index("ix_bank_deposits_user_id", "bank_deposits", ["user_id"])

    # withdrawals — user files pending; bank confirms (burn) or rejects.
    op.create_table(
        "withdrawals",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("amount_uzd", sa.BigInteger(), nullable=False),
        sa.Column("amount_wei", sa.String(80), nullable=False),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("tx_hash", sa.String(66), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_withdrawals_user_id", "withdrawals", ["user_id"])
    op.create_index("ix_withdrawals_status", "withdrawals", ["status"])

    # chain_events — indexer store, UNIQUE(tx_hash, log_index) idempotent upsert.
    op.create_table(
        "chain_events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            primary_key=True,
        ),
        sa.Column("tx_hash", sa.String(66), nullable=False),
        sa.Column("log_index", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(40), nullable=False),
        sa.Column("contract_address", sa.String(42), nullable=False),
        sa.Column("block_number", sa.BigInteger(), nullable=False),
        sa.Column("from_address", sa.String(42), nullable=True),
        sa.Column("to_address", sa.String(42), nullable=True),
        sa.Column("amount_wei", sa.String(80), nullable=True),
        sa.Column("answer", sa.String(80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.UniqueConstraint("tx_hash", "log_index", name="uq_chain_event_tx_log"),
    )
    op.create_index("ix_chain_events_event_type", "chain_events", ["event_type"])
    op.create_index("ix_chain_events_block_number", "chain_events", ["block_number"])
    op.create_index("ix_chain_events_from_address", "chain_events", ["from_address"])
    op.create_index("ix_chain_events_to_address", "chain_events", ["to_address"])


def downgrade() -> None:
    op.drop_index("ix_chain_events_to_address", table_name="chain_events")
    op.drop_index("ix_chain_events_from_address", table_name="chain_events")
    op.drop_index("ix_chain_events_block_number", table_name="chain_events")
    op.drop_index("ix_chain_events_event_type", table_name="chain_events")
    op.drop_table("chain_events")
    op.drop_index("ix_withdrawals_status", table_name="withdrawals")
    op.drop_index("ix_withdrawals_user_id", table_name="withdrawals")
    op.drop_table("withdrawals")
    op.drop_index("ix_bank_deposits_user_id", table_name="bank_deposits")
    op.drop_table("bank_deposits")
    op.drop_table("reserve_attestations")
